#ifndef RESOURCE_H      
#define RESOURCE_H

#define IDI_MAINICON						100

#define IDD_OPTIONSBOX						101
#define IDD_ABOUTBOX						102
#define IDD_LICENSEBOX						103
#define IDD_WINDOWLISTBOX					104
#define IDD_LAUNCHBOX						105

#define IDC_OPTIONSBOX_GROUPBOX				120
#define IDC_OPTIONSBOX_STATIC_PUTTYPATH		121
#define IDC_OPTIONSBOX_EDITBOX_PUTTYPATH	122
#define IDC_OPTIONSBOX_BUTTON_PUTTYPATH		123
#define IDC_OPTIONSBOX_STATIC_HOTKEY_WLIST	124
#define IDC_OPTIONSBOX_EDITBOX_HOTKEY_WLIST	125
#define IDC_OPTIONSBOX_STATIC_HOTKEY_LBOX	126
#define IDC_OPTIONSBOX_EDITBOX_HOTKEY_LBOX	127
#define IDC_OPTIONSBOX_BUTTON_STARTUP		128
#define IDC_OPTIONSBOX_BUTTON_DRAGDROP		129
#define IDC_OPTIONSBOX_BUTTON_SAVECUR		130

#define IDC_ABOUTBOX_BUTTON_LICENSE			120
#define IDC_ABOUTBOX_BUTTON_HOMEPAGE		121
#define IDC_ABOUTBOX_STATIC_VERSION			122

#define IDC_WINDOWLISTBOX_STATIC			120
#define IDC_WINDOWLISTBOX_LISTBOX			121
#define IDC_WINDOWLISTBOX_BUTTON_HIDE		122
#define IDC_WINDOWLISTBOX_BUTTON_SHOW		123
#define IDC_WINDOWLISTBOX_BUTTON_KILL		124

#define IDC_LAUNCHBOX_STATIC_TREEVIEW		120
#define IDC_LAUNCHBOX_GROUPBOX_TREEVIEW		121
#define IDC_LAUNCHBOX_BUTTON_NEW_FOLDER		122
#define IDC_LAUNCHBOX_BUTTON_NEW_SESSION	123
#define IDC_LAUNCHBOX_BUTTON_EDIT			124
#define IDC_LAUNCHBOX_BUTTON_RENAME			125
#define IDC_LAUNCHBOX_BUTTON_DELETE			126
#define IDC_LAUNCHBOX_BUTTON_MORE			127
#define IDC_LAUNCHBOX_COMBOBOX_HOTKEY		128
#define	IDC_LAUNCHBOX_EDITBOX_HOTKEY		129
#define	IDC_LAUNCHBOX_STATIC_HOTKEY			130
#define IDC_LAUNCHBOX_BUTTON_HOTKEY			131
#define IDC_LAUNCHBOX_STATIC_DIVIDER		133
#define IDC_LAUNCHBOX_CHECKBOX_LIMIT		134
#define IDC_LAUNCHBOX_EDITBOX_LIMIT1		135
#define IDC_LAUNCHBOX_CHECKBOX_RUN			136
#define IDC_LAUNCHBOX_STATIC_UNUSED2		137
#define IDC_LAUNCHBOX_STATIC_UNUSED3		138
#define IDC_LAUNCHBOX_COMBOBOX_LIMIT1		139
#define IDC_LAUNCHBOX_STATIC_UNUSED4		140
#define IDC_LAUNCHBOX_COMBOBOX_LIMIT2		141
#define IDC_LAUNCHBOX_STATIC_UNUSED5		142
#define IDC_LAUNCHBOX_COMBOBOX_LIMIT3		143
#define IDC_LAUNCHBOX_STATIC_UNUSED6		144
#define IDC_LAUNCHBOX_COMBOBOX_RUN1			145
#define IDC_LAUNCHBOX_STATIC_UNUSED7		146
#define IDC_LAUNCHBOX_COMBOBOX_RUN2			147
#define IDC_LAUNCHBOX_STATIC_UNUSED8		148
#define IDC_LAUNCHBOX_SPIN_HOTKEY			149

#endif /* RESOURCE_H */
