//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by plaunch.rc
//
#ifndef	RT_MANIFEST
#define RT_MANIFEST                     24
#endif
#define IDD_LAUNCHBOX_TAB0              106
#define IDD_LAUNCHBOX_TAB1              107
#define IDD_LAUNCHBOX_TAB2              108
#define IDD_LAUNCHBOX_TABGENERIC1       109
#define IDD_LAUNCHBOX_TABGENERIC2       110
#define IDC_LAUNCHBOX_EDITBOX_HOTKEY2   130
#define IDC_LAUNCHBOX_TAB0_EDITBOX_HOTKEY_EDIT 130
#define IDC_LAUNCHBOX_BUTTON_HOTKEY2    132
#define IDC_LAUNCHBOX_TAB0_BUTTON_HOTKEY_EDIT 132
#define IDC_LAUNCHBOX_EDITBOX_HOTKEY3   133
#define IDC_LAUNCHBOX_TAB0_EDITBOX_HOTKEY_KILL 133
#define IDC_LAUNCHBOX_BUTTON_HOTKEY3    134
#define IDC_LAUNCHBOX_TAB0_BUTTON_HOTKEY_KILL 134
#define IDC_OPTIONSBOX_EDITBOX_HOTKEY_CYCLEWINDOW 137
#define IDC_LAUNCHBOX_TAB1_CHECKBOX_AUTORUN_ATSTART 1000
#define IDC_LAUNCHBOX_TAB1_CHECKBOX_AUTORUN_ATSTART2 1002
#define IDC_LAUNCHBOX_TAB1_CHECKBOX_AUTORUN_ATNETWORKUP 1002
#define IDC_COMBO2                      1003
#define IDC_LAUNCHBOX_TABGENERIC1_COMBOBOX_FIND 1003
#define IDC_COMBO3                      1005
#define IDC_LAUNCHBOX_TABGENERIC1_COMBOBOX_ACTION1 1005
#define IDC_COMBO4                      1006
#define IDC_LAUNCHBOX_TABGENERIC1_COMBOBOX_ACTION2 1006
#define IDC_COMBO7                      1007
#define IDC_LAUNCHBOX_TABGENERIC1_COMBOBOX_ACTION3 1007
#define IDC_COMBO8                      1008
#define IDC_LAUNCHBOX_TABGENERIC1_COMBOBOX_ACTION4 1008
#define IDC_COMBO9                      1009
#define IDC_BUTTON1                     1009
#define IDC_LAUNCHBOX_TAB2_BUTTON_LIMIT_LOWER 1009
#define IDC_LAUNCHBOX_TABGENERIC1_COMBOBOX_ACTION5 1009
#define IDC_LAUNCHBOX_TAB1_CHECKBOX_AUTORUN_ATSTART5 1010
#define IDC_COMBO10                     1010
#define IDC_LAUNCHBOX_TAB1_CHECKBOX_AUTORUN_ATSTOP 1010
#define IDC_LAUNCHBOX_TAB2_CHECKBOX_LIMIT_ENABLE 1010
#define IDC_LAUNCHBOX_TABGENERIC1_COMBOBOX_ACTION6 1010
#define IDC_BUTTON2                     1011
#define IDC_LAUNCHBOX_TAB1_BUTTON_ATNETWORKUP 1011
#define IDC_LAUNCHBOX_TAB2_CHECKBOX_LIMIT_LOWER 1011
#define IDC_LAUNCHBOX_TABGENERIC1_COMBOBOX_ACTION7 1011
#define IDC_LAUNCHBOX_TAB1_CHECKBOX_AUTORUN_ATSTART6 1012
#define IDC_LAUNCHBOX_TAB1_CHECKBOX_AUTORUN_ATNETWORKDOWN 1012
#define IDC_LAUNCHBOX_TAB2_CHECKBOX_LIMIT_UPPER 1012
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION1 1012
#define IDC_LAUNCHBOX_TABGENERIC_BUTTON_BACK 1013
#define IDC_COMBO11                     1014
#define IDC_BUTTON4                     1014
#define IDC_LAUNCHBOX_TAB2_EDITBOX_LIMIT_LOWER 1014
#define IDC_LAUNCHBOX_TABGENERIC_BUTTON_MORE 1014
#define IDC_COMBO12                     1015
#define IDC_BUTTON5                     1015
#define IDC_LAUNCHBOX_TAB1_BUTTON_AUTORUN_ATSTOP 1015
#define IDC_LAUNCHBOX_TAB2_SPIN_LOWER   1015
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION2 1015
#define IDC_COMBO13                     1016
#define IDC_LAUNCHBOX_TAB0_EDITBOX_HOTKEY_LAUNCH 1016
#define IDC_LAUNCHBOX_TAB2_EDITBOX_LIMIT_UPPER 1016
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION3 1016
#define IDC_LAUNCHBOX_TAB0_BUTTON_HOTKEY_LAUNCH 1017
#define IDC_LAUNCHBOX_TAB2_SPIN_LIMIT_UPPER 1017
#define IDC_COMBO15                     1018
#define IDC_LAUNCHBOX_TAB1_BUTTON_AUTORUN_ATSTART 1018
#define IDC_LAUNCHBOX_TAB1_BUTTON_AUTORUN_ATNETWORKDOWN 1019
#define IDC_LAUNCHBOX_TAB2_BUTTON_LIMIT_UPPER 1020
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION4 1021
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION5 1022
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION6 1023
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION7 1024
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION8 1025
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION9 1026
#define IDC_LAUNCHBOX_TABGENERIC2_COMBOBOX_ACTION10 1027
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
